### ISSUE TITLE
Behavior when passing tracestate of ''

### ISSUE THREAD

**Issue by bizob2828** [w3c/distributed-tracing#470]
I have a question/need confirmation about what is correct in a certain use case.  This test was added in #417: https://github.com/w3c/trace-context/blob/main/test/test.py#L501.  It is implying that if you pass in a traceparent header of `''` we should not add additional context.  Based on the driver for #417 it just seems like it was a side effect of the PR fix but not asserting spec behavior. 

In `3.3.1.1 tracestate Header Field Values` of spec:

> Empty and whitespace-only list members are allowed. Vendors MUST accept empty tracestate headers but SHOULD avoid sending them. Empty list members are allowed in tracestate because it is difficult for a vendor to recognize the empty value when multiple tracestate headers are sent. Whitespace characters are allowed for a similar reason, as some vendors automatically inject whitespace after a comma separator, even in the case of an empty header.

You can also see the .Net agent team at New Relic just pinned the sha to run their tests to before this change https://github.com/newrelic/newrelic-dotnet-agent/pull/162.

**Comment by dyladan** [comment]
The title mentions traceparent but the test you've linked is testing empty tracestate

**Comment by bizob2828** [comment]
> The title mentions traceparent but the test you've linked is testing empty tracestate

Oops, I updated @dyladan.  I meant to call out empty tracestate

**Comment by dyladan** [comment]
So the test you are proposing to change enforces the behavior that if tracestate is empty, then it should be removed. Your request would be: "If a service receives an empty tracestate, they should be allowed to create one"

Does that sounds like a good summary? if so, I agree with it 100%

**Comment by bizob2828** [comment]
> So the test you are proposing to change enforces the behavior that if tracestate is empty, then it should be removed. Your request would be: "If a service receives an empty tracestate, they should be allowed to create one"
> 
> 
> 
> Does that sounds like a good summary? if so, I agree with it 100%

That sounds about right
