### ISSUE TITLE
Start Wide Review for Trace Context Level 2 Spec

### ISSUE THREAD

**Issue by kalyanaj** [w3c/distributed-tracing#492]
- [x] Working draft available for wide review: https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fwww.w3.org%2FTR%2Ftrace-context-1%2F&doc2=https%3A%2F%2Fwww.w3.org%2FTR%2F2022%2FWD-trace-context-2-20220929%2F
- [x] Send notifications to groups listed in [Charter coordination section](https://www.w3.org/2020/08/distributed-tracing-wg-charter.html#coordination): Web Performance, IETF HTTP WG
- [x] A11y review
- [x] I18n review
- [x] Privacy review
- [ ] Security review
- [x] TAG review

See also [How to do Wide Review](https://www.w3.org/Guide/documentreview/).

**Comment by kalyanaj** [comment]
Filed request for TAG review: https://github.com/w3ctag/design-reviews/issues/777

**Comment by kalyanaj** [comment]
Filed request for Privacy review: https://github.com/w3cping/privacy-request/issues/103

**Comment by kalyanaj** [comment]
Filed request for Security review: https://github.com/w3c/security-request/issues/40

**Comment by kalyanaj** [comment]
Filed request for i18n review: https://github.com/w3c/i18n-request/issues/193

**Comment by kalyanaj** [comment]
Closing this as this is done, and we have filed the CR transition request.

**Comment by plehegar** [comment]
HTTP WG review: https://lists.w3.org/Archives/Public/ietf-http-wg/2023JanMar/0061.html
