### ISSUE TITLE
Need to publish latest draft of trace-context-2

### ISSUE THREAD

**Issue by kalyanaj** [w3c/distributed-tracing#493]
The latest working draft of the trace-context level 2 spec needs to be published, so that we can reference it in various reviews. Should it be to https://www.w3.org/TR/trace-context-2/?  Right now, we have the following:

- https://www.w3.org/TR/trace-context-1/:  Level 1 spec (in recommendation status)
- https://w3c.github.io/trace-context/: Latest spec (from the main branch)
- <we need one for the level-2 draft> - looking at the above convention, it looks like it needs to be published to https://www.w3.org/TR/trace-context-2/?

**Comment by plehegar** [comment]
See https://github.com/w3c/transitions/issues/458

**Comment by kalyanaj** [comment]
@plehegar Thanks for filing the transition request, I was looking at the current diff link and I see that it includes information such as "section 4. Trace Context HTTP Response Headers Format" which is unexpected since it exists only in the main branch and not in the level 2 branch. 

Hence, wanted to double check if the level 2 branch was chosen for this diff (or if there is some other reason this content is unexpectedly showing up in the diff). Cc: @SergeyKanzhelev , @dyladan.

This is the diff link I was looking at: https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fwww.w3.org%2FTR%2Ftrace-context-1%2F&doc2=https%3A%2F%2Flabs.w3.org%2Fspec-generator%2F%3Ftype%3Drespec%26url%3Dhttps%3A%2F%2Fw3c.github.io%2Ftrace-context%2F%3FspecStatus%3DWD%26shortName%3Dfoo

**Comment by kalyanaj** [comment]
Thanks @plehegar for the publishing, closing this issue now.
