### ISSUE TITLE
Adopt either span-id or parent-id for section headings

### ISSUE THREAD

**Issue by pes10k** [w3c/distributed-tracing#509]
This issue is filed from PING review [#103](https://github.com/w3cping/privacy-request/issues/103)

This isn't a blocking / needs-resolution concern, but as best I can tell from my read, the proposal uses span-id and parent-id interchangeably, even in the document's headers.  For example, 3.2.2.4 uses the term "parent-id" while all of section 10 uses "span-id".  I suggest using a single name here (at least for the document's organization / headings) to make it easier for the reader.

**Comment by kalyanaj** [comment]
Thanks @pes10k for filing this issue. 

Upon investigating this a bit, I see that https://github.com/w3c/trace-context/blob/main/http_header_format_rationale.md#spanparent-nomenclature describes the rationale and historical context on why the term parent-id was chosen.  In general, span-id refers to the current span while parent-id refers to the parent's span-id or equivalent (in non span-based systems).

I was initially thinking that changing the term parent-id to "parent-span-id" could make things clearer, however after reading the above rationale for why the generic name "parent-id" was chosen, I am inclined to leave this terminology as is. Further, this terminology didn't change in the Level 2 of the spec, and has been part of the official Level 1 standard.

**Comment by pes10k** [comment]
okie dokie, feel free to close out this issue then

**Comment by kalyanaj** [comment]
Closing per the above discussion.

**Comment by yurishkuro** [comment]
span-id terminology would imply a span model, which is not a requirement of the spec. The use of parent-id avoids giving an explicit name to the parent entity and could be interpreted as "parent span id" or "parent event id".
