### ISSUE TITLE
Change the defining document for HTTP from RFC7230 to RFC9110

### ISSUE THREAD

**Issue by kalyanaj** [w3c/distributed-tracing#519]
This is feedback from the IETF HTTP WG:

"The defining document for HTTP is now RFC9110, not RFC7230/1; please update your references accordingly."

**Comment by kalyanaj** [comment]
Re-assigning per our discussion in the WG meeting, thanks Bastian!

**Comment by basti1302** [comment]
Per meeting: We probably want to make that change for level 2, but not backport it to level 1. Some research is required to check whether that change has any impact on our spec (it shouldn't)
