### ISSUE TITLE
Does this specification define a way to handle retries?

### ISSUE THREAD

**Issue by ben221199** [w3c/distributed-tracing#549]
I don't see the words "retry" or "retries" anywhere in the specification. However, it seems possible that the combination of `trace-id` and `parent-id` can be used for it. For example, in my case I had to build a HTTP endpoint for my monday.com integrations. I use both the `trace-id` and `parent-id` to detect if monday.com does a retry on my endpoint when the previous one failed. The problem is that I don't know if Traceparent is actually meant for that purpose.

**Comment by kalyanaj** [comment]
We discussed in the working group meeting. The short answer is that this is outside the scope of the TraceContext specification: it is up to a higher layer (e.g., OpenTelemetry HTTP semantic conventions define the retry semantics) to define this.

**Comment by ben221199** [comment]
So if I understand correctly, you say it is the task of another HTTP header, because `Traceparent` is only for tracing the hierarchy of distributed trigger, so `Traceparent` changing or not is up to the decisions of webhook provider?

In that case, if it is able to change between retries, I have the feeling that I use the header possibily incorrectly and that there is no documentated way to distinguish a retry from monday.com. 😬

**Comment by basti1302** [comment]
Correct. I personally wouldn't recommend using `traceparent` or anything from this spec to detect HTTP retries. It is not what the spec is intended for. You would rely on the implementation details of how the implementation of this spec on the client side handles retries. Some implementations might send a new span ID with HTTP retries, some might reuse the existing one. Both behaviors are valid, the spec deliberately does not mandate either. So this does not give you a reliable detection mechanism.

**Comment by ben221199** [comment]
Understood. I will look for other headers that monday.com sends to me, but I don't think there is a better header. In that case I will continue to assume that monday.com keeps the same ID.
