### ISSUE TITLE
request for clarification re size of parent-id

### ISSUE THREAD

**Issue by helmavdl** [w3c/distributed-tracing#574]
We are looking to adopt this standard but we are wondering why the traceparent is a single identifier that consists of 2 parts where the parent-id is only 8 bytes.

If the parent-id would be a separate id (separate HTTP header) there would be no size limit necessary and it could hold e.g. a UUID. In fact it could also be replaced by the commonly used request id.

Our intention is to implement tracing identifiers across systems of different organizations which can each contain multiple components. Maybe this is not the intended purpose of this standard?

**Comment by basti1302** [comment]
> Our intention is to implement tracing identifiers across systems of different organizations which can each contain multiple components. Maybe this is not the intended purpose of this standard?

This is definitely (one of) the intended purposes of this standard. 

16 byte trace IDs and 8 byte span IDs (the parent ID part of the header) have pretty much become a de-facto standard in distributed tracing. **Could you please elaborate what is your concern with regard to the length?** 

With respect to your question "why not a separate header" - there are multiple good reasons:
* size overhead: header names take up space in the request size, so having only one header is more efficient in terms of payload size
* complexity: with two separate headers for trace ID and span ID, any implementation would have to deal with a few new edge cases - what if one header is present but the other is not

Last but not least, having no size limit on the parent ID (or even not specifying its format at all) would be detrimental to one stated goal of the specification, which is cross-vendor compatible trace context propagation.

**Comment by helmavdl** [comment]
Re length: as far as I understand the standard, it is the intention that when a request results in a new request to a different component the traceparent is parsed, the trace ID is copied and suffixed with a new parent ID. 
In our case one incoming request could result in multiple requests to different independent systems in different organizations. The chance of producing a duplicate parent ID by 2 independent organizations is greater with 8 bytes than when the parent ID could e.g. be a UUID. I understand the argument that a format needs to be specified to allow better compatibility.

Re size overhead: would that really be an issue?
Re complexity: Could you elaborate on the edge cases?

Finally, an issue that was raised here yesterday: 
our organization deals with sensitive information in the requests/responses. Of course ample measurements are taken to make sure this information is exchanged in a secure way between permitted participants only, and the logs are also stored securely with only restricted acces.
However, the very purpose of being able to track requests and responses across systems for e.g. troubleshooting purposes also allows for tracking activity/information exchange for persons. How to deal with this privacy issue?

**Comment by basti1302** [comment]
> Re length: as far as I understand the standard, it is the intention that when a request results in a new request to a different component the traceparent is parsed, the trace ID is copied and suffixed with a new parent ID.

That is correct.

> In our case one incoming request could result in multiple requests to different independent systems in different organizations.

This is basically true for every non-trivial application, so this not at all a unique situation.

> The chance of producing a duplicate parent ID by 2 independent organizations is greater with 8 bytes than when the parent ID could e.g. be a UUID. I understand the argument that a format needs to be specified to allow better compatibility.

**Note that the span ID/parent ID only needs to be unique within a single trace, that is, for any given value of trace ID.** But even ignoring that: when the parent ID is created at random the chances of creating the same parent ID twice within any reasonable time span (months, years) is _extremely_ low. If I have the math right the chances for two randomly created 8 byte strings being identical is 1 / (2 ^ 64), right?

A while back, a lot of distributed tracing system used to use 8 bytes for the trace ID, which actually needs to be unique. This was not problem in practice even for users with high load. Nevertheless, the industry shifted to 16 bytes for the trace ID to make trace ID clashes completely unlikely.
 
> Re size overhead: would that really be an issue?

Yes, absolutely. For a good chunk of users of the the spec, especially companies running things at scale, every byte matters.

> Re complexity: Could you elaborate on the edge cases?

The spec would need to lay out rules what the behavior is when only the trace ID header is present in an incoming request, but the parent ID is not, and vice versa. Granted, this could be done, so nevermind this particular argument.
 
> Finally, an issue that was raised here yesterday: our organization deals with sensitive information in the requests/responses. Of course ample measurements are taken to make sure this information is exchanged in a secure way between permitted participants only, and the logs are also stored securely with only restricted acces. However, the very purpose of being able to track requests and responses across systems for e.g. troubleshooting purposes also allows for tracking activity/information exchange for persons. How to deal with this privacy issue?

This is, to some degree, outside of the scope of this specification I think. I hear what you are saying and there is indeed an (albeit theoretical) tradeoff here: If in your current system (without any distributed tracing facilities), it is really impossible to associate an incoming request at the edge (which might deal with personally identifiable information (PII)) to requests happening further downstream, then these downstream requests cannot be correlated with that PII. Introducing distributed tracing would then enable that correlation for users with proper access the systems involved. In practice, I would challenge the assumption that this correlation cannot be done by other means already today (via timestamps, request IDs, ...).

Last but not least, maybe a word of advice: The way you phrase these questions make me think that you are planning on implementing distributed tracing from scratch, on your own. I think this is very rarely done these days, to be honest. Most people will either use the dominant open standard  [OpenTelemetry](https://opentelemetry.io/) and its readily available open source components for this, or buy a product from one the observability vendors out there and integrate it into their system. Going that route, all of these solutions will also handle generating trace IDs and parent IDs for you.

**Comment by hepabolu** [comment]
Slightly related question: I see the version in this repo is labeled as `W3C Editor's Draft`. We want to conform to this standard, but are very interested in using the `traceresponse` as well, which is not in the current published version. Any indication of when the version in this repo will be published? Are you months or years away from final publication?

**Comment by basti1302** [comment]
Realistically, at this point it is unlikely that we will be able to publish something around `traceresponse` in the next few weeks or months. Different factors play into this, the two most important ones are that https://github.com/w3c/trace-context/issues/573 and work around sampling probability have now been scheduled to be worked on before the `traceresponse` aspect, and the very limited resources in terms of capacity and people power in this WG.

Realistically, OTel will probably move more quickly in that regard than the W3C trace context spec, you might want to keep your eyes peeled what happens in that space.

**Comment by basti1302** [comment]
Since the original question has been answered and there was no new input on the size of the parent id field, I'll go ahead and close this issue out.
